### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by JannisNe** [simeonreusch/fpbot#101]
**Describe the bug**
When running `fp.psffit()` apparently a directory is trying to be used that does not necesarrily exist.

**To Reproduce**
Steps to reproduce the behavior, just follow the steps as described in the README.

**Expected behavior**
Works.

**Screenshots**
```
----------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[18], line 1
----> 1 pl.psffit()

File ~/opt/miniconda3/envs/fpbot/lib/python3.10/site-packages/fpbot/pipeline.py:664, in ForcedPhotometryPipeline.psffit(self, nprocess, force_refit)
    661 if number_of_fitted_datapoints_expected > fitted_datapoints or force_refit:
    662     self.logger.info(f"{name} ({i+1} of {objects_total}): Fitting PSF.")
--> 664     fp.run_forcefit(
    665         nprocess=nprocess,
    666         store=True,
    667         force_refit=force_refit,
    668         no_badsub=False,
    669     )
    671     fp.store()
    673     lastfit = Time(time.time(), format="unix", scale="utc").jd

File ~/opt/miniconda3/envs/fpbot/lib/python3.10/site-packages/ztflc/forcephotometry.py:166, in ForcePhotometry.run_forcefit(self, indexes, update_diffdata, store, no_badsub, force_refit, nprocess)
    164     self._data_forcefit = pd.DataFrame(dataout_final)
    165     if store:
--> 166         self.store()
    168 else:
    169     for i in tqdm(indexes):

File ~/opt/miniconda3/envs/fpbot/lib/python3.10/site-packages/ztflc/forcephotometry.py:93, in ForcePhotometry.store(self, filename, mode)
     91 oldmask = os.umask(0o002)
     92 if len(self._data_forcefit) > 0:
---> 93     self._data_forcefit.to_csv(filename, index=False, mode=mode)

File ~/opt/miniconda3/envs/fpbot/lib/python3.10/site-packages/pandas/util/_decorators.py:211, in deprecate_kwarg.<locals>._deprecate_kwarg.<locals>.wrapper(*args, **kwargs)
    209     else:
    210         kwargs[new_arg_name] = new_arg_value
--> 211 return func(*args, **kwargs)

File ~/opt/miniconda3/envs/fpbot/lib/python3.10/site-packages/pandas/core/generic.py:3720, in NDFrame.to_csv(self, path_or_buf, sep, na_rep, float_format, columns, header, index, index_label, mode, encoding, compression, quoting, quotechar, lineterminator, chunksize, date_format, doublequote, escapechar, decimal, errors, storage_options)
   3709 df = self if isinstance(self, ABCDataFrame) else self.to_frame()
   3711 formatter = DataFrameFormatter(
   3712     frame=df,
   3713     header=header,
   (...)
   3717     decimal=decimal,
   3718 )
-> 3720 return DataFrameRenderer(formatter).to_csv(
   3721     path_or_buf,
   3722     lineterminator=lineterminator,
   3723     sep=sep,
   3724     encoding=encoding,
   3725     errors=errors,
   3726     compression=compression,
   3727     quoting=quoting,
   3728     columns=columns,
   3729     index_label=index_label,
   3730     mode=mode,
   3731     chunksize=chunksize,
   3732     quotechar=quotechar,
   3733     date_format=date_format,
   3734     doublequote=doublequote,
   3735     escapechar=escapechar,
   3736     storage_options=storage_options,
   3737 )

File ~/opt/miniconda3/envs/fpbot/lib/python3.10/site-packages/pandas/util/_decorators.py:211, in deprecate_kwarg.<locals>._deprecate_kwarg.<locals>.wrapper(*args, **kwargs)
    209     else:
    210         kwargs[new_arg_name] = new_arg_value
--> 211 return func(*args, **kwargs)

File ~/opt/miniconda3/envs/fpbot/lib/python3.10/site-packages/pandas/io/formats/format.py:1189, in DataFrameRenderer.to_csv(self, path_or_buf, encoding, sep, columns, index_label, mode, compression, quoting, quotechar, lineterminator, chunksize, date_format, doublequote, escapechar, errors, storage_options)
   1168     created_buffer = False
   1170 csv_formatter = CSVFormatter(
   1171     path_or_buf=path_or_buf,
   1172     lineterminator=lineterminator,
   (...)
   1187     formatter=self.fmt,
   1188 )
-> 1189 csv_formatter.save()
   1191 if created_buffer:
   1192     assert isinstance(path_or_buf, StringIO)

File ~/opt/miniconda3/envs/fpbot/lib/python3.10/site-packages/pandas/io/formats/csvs.py:241, in CSVFormatter.save(self)
    237 """
    238 Create the writer & save.
    239 """
    240 # apply compression and byte/text conversion
--> 241 with get_handle(
    242     self.filepath_or_buffer,
    243     self.mode,
    244     encoding=self.encoding,
    245     errors=self.errors,
    246     compression=self.compression,
    247     storage_options=self.storage_options,
    248 ) as handles:
    249 
    250     # Note: self.encoding is irrelevant here
    251     self.writer = csvlib.writer(
    252         handles.handle,
    253         lineterminator=self.lineterminator,
   (...)
    258         quotechar=self.quotechar,
    259     )
    261     self._save()

File ~/opt/miniconda3/envs/fpbot/lib/python3.10/site-packages/pandas/io/common.py:734, in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    732 # Only for write methods
    733 if "r" not in mode and is_path:
--> 734     check_parent_directory(str(handle))
    736 if compression:
    737     if compression != "zstd":
    738         # compression libraries do not like an explicit text-mode

File ~/opt/miniconda3/envs/fpbot/lib/python3.10/site-packages/pandas/io/common.py:597, in check_parent_directory(path)
    595 parent = Path(path).parent
    596 if not parent.is_dir():
--> 597     raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")

OSError: Cannot save file into a non-existent directory: '/Users/jannisnecker/ztf_dataforcephotometry'
```

**Additional context**
`pl = ForcedPhotometryPipeline(file_or_name="ZTF19adgzidh", daysago=3000, nprocess=6, ra=225.4345633, dec=41.2829577)`

**Comment by simeonreusch** [comment]
Add a slash at the end of your ztfdata env var 😉On 30. Apr 2023, at 14:29, Jannis Necker ***@***.***> wrote:﻿
Describe the bug
When running fp.psffit() apparently a directory is trying to be used that does not necesarrily exist.
To Reproduce
Steps to reproduce the behavior, just follow the steps as described in the README.
Expected behavior
Works.
Screenshots
----------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[18], line 1
----> 1 pl.psffit()

File ~/opt/miniconda3/envs/fpbot/lib/python3.10/site-packages/fpbot/pipeline.py:664, in ForcedPhotometryPipeline.psffit(self, nprocess, force_refit)
    661 if number_of_fitted_datapoints_expected > fitted_datapoints or force_refit:
    662     self.logger.info(f"{name} ({i+1} of {objects_total}): Fitting PSF.")
--> 664     fp.run_forcefit(
    665         nprocess=nprocess,
    666         store=True,
    667         force_refit=force_refit,
    668         no_badsub=False,
    669     )
    671     fp.store()
    673     lastfit = Time(time.time(), format="unix", scale="utc").jd

File ~/opt/miniconda3/envs/fpbot/lib/python3.10/site-packages/ztflc/forcephotometry.py:166, in ForcePhotometry.run_forcefit(self, indexes, update_diffdata, store, no_badsub, force_refit, nprocess)
    164     self._data_forcefit = pd.DataFrame(dataout_final)
    165     if store:
--> 166         self.store()
    168 else:
    169     for i in tqdm(indexes):

File ~/opt/miniconda3/envs/fpbot/lib/python3.10/site-packages/ztflc/forcephotometry.py:93, in ForcePhotometry.store(self, filename, mode)
     91 oldmask = os.umask(0o002)
     92 if len(self._data_forcefit) > 0:
---> 93     self._data_forcefit.to_csv(filename, index=False, mode=mode)

File ~/opt/miniconda3/envs/fpbot/lib/python3.10/site-packages/pandas/util/_decorators.py:211, in deprecate_kwarg.<locals>._deprecate_kwarg.<locals>.wrapper(*args, **kwargs)
    209     else:
    210         kwargs[new_arg_name] = new_arg_value
--> 211 return func(*args, **kwargs)

File ~/opt/miniconda3/envs/fpbot/lib/python3.10/site-packages/pandas/core/generic.py:3720, in NDFrame.to_csv(self, path_or_buf, sep, na_rep, float_format, columns, header, index, index_label, mode, encoding, compression, quoting, quotechar, lineterminator, chunksize, date_format, doublequote, escapechar, decimal, errors, storage_options)
   3709 df = self if isinstance(self, ABCDataFrame) else self.to_frame()
   3711 formatter = DataFrameFormatter(
   3712     frame=df,
   3713     header=header,
   (...)
   3717     decimal=decimal,
   3718 )
-> 3720 return DataFrameRenderer(formatter).to_csv(
   3721     path_or_buf,
   3722     lineterminator=lineterminator,
   3723     sep=sep,
   3724     encoding=encoding,
   3725     errors=errors,
   3726     compression=compression,
   3727     quoting=quoting,
   3728     columns=columns,
   3729     index_label=index_label,
   3730     mode=mode,
   3731     chunksize=chunksize,
   3732     quotechar=quotechar,
   3733     date_format=date_format,
   3734     doublequote=doublequote,
   3735     escapechar=escapechar,
   3736     storage_options=storage_options,
   3737 )

File ~/opt/miniconda3/envs/fpbot/lib/python3.10/site-packages/pandas/util/_decorators.py:211, in deprecate_kwarg.<locals>._deprecate_kwarg.<locals>.wrapper(*args, **kwargs)
    209     else:
    210         kwargs[new_arg_name] = new_arg_value
--> 211 return func(*args, **kwargs)

File ~/opt/miniconda3/envs/fpbot/lib/python3.10/site-packages/pandas/io/formats/format.py:1189, in DataFrameRenderer.to_csv(self, path_or_buf, encoding, sep, columns, index_label, mode, compression, quoting, quotechar, lineterminator, chunksize, date_format, doublequote, escapechar, errors, storage_options)
   1168     created_buffer = False
   1170 csv_formatter = CSVFormatter(
   1171     path_or_buf=path_or_buf,
   1172     lineterminator=lineterminator,
   (...)
   1187     formatter=self.fmt,
   1188 )
-> 1189 csv_formatter.save()
   1191 if created_buffer:
   1192     assert isinstance(path_or_buf, StringIO)

File ~/opt/miniconda3/envs/fpbot/lib/python3.10/site-packages/pandas/io/formats/csvs.py:241, in CSVFormatter.save(self)
    237 """
    238 Create the writer & save.
    239 """
    240 # apply compression and byte/text conversion
--> 241 with get_handle(
    242     self.filepath_or_buffer,
    243     self.mode,
    244     encoding=self.encoding,
    245     errors=self.errors,
    246     compression=self.compression,
    247     storage_options=self.storage_options,
    248 ) as handles:
    249 
    250     # Note: self.encoding is irrelevant here
    251     self.writer = csvlib.writer(
    252         handles.handle,
    253         lineterminator=self.lineterminator,
   (...)
    258         quotechar=self.quotechar,
    259     )
    261     self._save()

File ~/opt/miniconda3/envs/fpbot/lib/python3.10/site-packages/pandas/io/common.py:734, in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    732 # Only for write methods
    733 if "r" not in mode and is_path:
--> 734     check_parent_directory(str(handle))
    736 if compression:
    737     if compression != "zstd":
    738         # compression libraries do not like an explicit text-mode

File ~/opt/miniconda3/envs/fpbot/lib/python3.10/site-packages/pandas/io/common.py:597, in check_parent_directory(path)
    595 parent = Path(path).parent
    596 if not parent.is_dir():
--> 597     raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")

OSError: Cannot save file into a non-existent directory: '/Users/jannisnecker/ztf_dataforcephotometry'

Additional context
pl = ForcedPhotometryPipeline(file_or_name="ZTF19adgzidh", daysago=3000, nprocess=6, ra=225.4345633, dec=41.2829577)
